// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// jrpg
arma::vec jrpg(arma::vec b, arma::vec z);
RcppExport SEXP _jrpg_jrpg(SEXP bSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(jrpg(b, z));
    return rcpp_result_gen;
END_RCPP
}
// rpg_devroye
double rpg_devroye(int b, double z);
RcppExport SEXP _jrpg_rpg_devroye(SEXP bSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(rpg_devroye(b, z));
    return rcpp_result_gen;
END_RCPP
}
// rpg_na
double rpg_na(double b, double z);
RcppExport SEXP _jrpg_rpg_na(SEXP bSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(rpg_na(b, z));
    return rcpp_result_gen;
END_RCPP
}
// rpg_gamma
double rpg_gamma(double b, double z, int trunc);
RcppExport SEXP _jrpg_rpg_gamma(SEXP bSEXP, SEXP zSEXP, SEXP truncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type trunc(truncSEXP);
    rcpp_result_gen = Rcpp::wrap(rpg_gamma(b, z, trunc));
    return rcpp_result_gen;
END_RCPP
}
// rpg_sp
double rpg_sp(double b, double z, int maxiter);
RcppExport SEXP _jrpg_rpg_sp(SEXP bSEXP, SEXP zSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(rpg_sp(b, z, maxiter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jrpg_jrpg", (DL_FUNC) &_jrpg_jrpg, 2},
    {"_jrpg_rpg_devroye", (DL_FUNC) &_jrpg_rpg_devroye, 2},
    {"_jrpg_rpg_na", (DL_FUNC) &_jrpg_rpg_na, 2},
    {"_jrpg_rpg_gamma", (DL_FUNC) &_jrpg_rpg_gamma, 3},
    {"_jrpg_rpg_sp", (DL_FUNC) &_jrpg_rpg_sp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_jrpg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
