# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Draw a vector of Polya-Gamma latent random variables with parameters `b` and `z`
#'
#' @param b vector of parameters for $PG(b,z)$ random variable.
#' @param z vector of parameters for $PG(b,z)$ random variable.
#' @returns column vector of \code{length(b)} containing $PG(b,z)$ random variates.
#'
#' @export
jrpg <- function(b, z) {
    .Call(`_jrpg_jrpg`, b, z)
}

rpg_devroye <- function(b, z) {
    .Call(`_jrpg_rpg_devroye`, b, z)
}

rpg_na <- function(b, z) {
    .Call(`_jrpg_rpg_na`, b, z)
}

rpg_gamma <- function(b, z) {
    .Call(`_jrpg_rpg_gamma`, b, z)
}

rpg_sp <- function(b, z, maxiter) {
    .Call(`_jrpg_rpg_sp`, b, z, maxiter)
}

