# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiple draw polya gamma latent variable for var c[i] with size b[i]
#'
#' @param b vector of binomial sizes
#' @param z vector of parameters
#' @returns Eigen::VectorXd
#' @export
jrpg <- function(b, z) {
    .Call(`_jrpg_jrpg`, b, z)
}

rpg_gamma <- function(b, z) {
    .Call(`_jrpg_rpg_gamma`, b, z)
}

